### ISSUE TITLE
动态界面

### ISSUE THREAD

**Issue by Liaoer** [stoneshih99/RedPointSystem#1]
如果界面是动态创建的，这种结构是否就有限制了？不能提前预知动态创建的节点里数据

**Comment by stoneshih99** [comment]
> 如果界面是动态创建的，这种结构是否就有限制了？不能提前预知动态创建的节点里数据
是可行的! 以範例來說節點的關聯定義都是在 RedPointTreeMapExample 並非在 Hierarchy 上，所以你只要自己的 GameObject 梆上 extends RedPointAbstractNode 的 Component  就可以了。

**Comment by Liaoer** [comment]
谢谢，明白了
